name: "CI"
on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable && rustup set profile minimal
      - run: cargo build --verbose
